# Generated by Django 5.0.4 on 2024-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default='2024-05-13 19:58'),
        ),
    ]
